name: CNN
model_config:
  p: 97
  num_channels: 1
  kernel_sizes:
    - [2, 5]
    - [1, 5]
  strides: [1, 1]
  paddings:
    - [0, 0]
    - [0, 0]
  num_hiddens: [16, 32]
  num_outputs: 97
  dropout_rate: 0.1
  hidden_dim: 256
checkpoint_path: null
strict_load: True
