name: Transformer
transformer_config:
  vocab_size: 99
  embed_dim: 128
  ffn_num_hiddens: 256
  num_heads: 2
  num_layers: 2
  dropout: 0.01
  decice: cuda
checkpoint_path:
strict_load: True