defaults:
  - datasets: mathop
  - model: CNN
  - grokfast: grokfastEMA
  - _self_

loss:
  name: CrossEntropyCNN


optimizer:
  name: Adam
  lr: 0.01
  momentum: 0.9
  weight_decay: 1e-4
  betas: [0.9, 0.999]
  eps: 1e-8


train:
  eval_every: 10
  max_steps: 1e6
  stop_condi: 0.999
  stop_epochs: 1000
  log_dir: ./logs
  checkpoint_path: 
  save_every: 1000
  using_grokfast: 0

